// for root layout page of signin signup and verify...
import type { Metadata } from "next";
// 'use client'
import localFont from "next/font/local";
import '../globals.css'

// import  AuthProvider  from "./components/providers/AuthProvider";
// AuthProvider
import { Toaster } from "@/components/ui/toaster"
import AuthProvider from "@/context/AuthProvider";

const geistSans = localFont({
  src: [
    { path: "../fonts/GeistVF.woff", weight: "100 900" },
  ],
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: [{ path: "../fonts/GeistMonoVF.woff", weight: "100 900" }],
  variable: "--font-geist-mono",
});



export const metadata: Metadata = {
  title : 'Dashboard',
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  
    // console.log(getTitle())
  return (
    <html lang="en">
     
      <AuthProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {children}
          <Toaster />
        </body>
      </AuthProvider>

    </html>
  );
}
